name: Ubuntu CI/CD

# triggers
on:
  push:
  pull_request:
  workflow_dispatch:

# define job name and sequence
jobs:
  build:
    name: Build, Test, and Lint

    # runner os
    runs-on: ubuntu-latest

    # cache build deps
    steps:
      - name: Cache
        uses: actions/cache@v3.0.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      # setup nodejs
      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: 14 # latest LTS version

      # check out repo
      - name: Checkout
        uses: actions/checkout@v2

      # install node_modules
      - name: Install
        run: npm i

      # build package
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      # test package
      - name: Test
        run: npm test

      # lint package
      - name: Lint
        run: npm run lint

      # archive production artifact
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist
